export const mockData = [
  {
    id: "A",
    firstName: "Karlotte",
    lastName: "Gallant",
    age: 22,
    visits: 408,
    progress: 54.32,
    status: "active",
  },
  {
    id: "B",
    firstName: "Caty",
    lastName: "Heasley",
    age: 27,
    visits: 434,
    progress: 78.4,
    status: "inactive",
  },
  {
    id: "C",
    firstName: "Rhianna",
    lastName: "Glasser",
    age: 50,
    visits: 451,
    progress: 42.83,
    status: "inactive",
  },
  {
    id: "D",
    firstName: "Matthus",
    lastName: "Wilcocke",
    age: 18,
    visits: 588,
    progress: 18.29,
    status: "active",
  },
  {
    id: "E",
    firstName: "Jenni",
    lastName: "Kemster",
    age: 82,
    visits: 961,
    progress: 74.82,
    status: "pending",
  },
  // {
  //   firstName: "Clementius",
  //   lastName: "Messenbird",
  //   age: 21,
  //   visits: 65,
  //   progress: 98.29,
  //   status: "pending",
  // },
  // {
  //   firstName: "Elsa",
  //   lastName: "Aspey",
  //   age: 76,
  //   visits: 63,
  //   progress: 50.24,
  //   status: "active",
  // },
  // {
  //   firstName: "Hugh",
  //   lastName: "Arro",
  //   age: 60,
  //   visits: 79,
  //   progress: 95.51,
  //   status: "pending",
  // },
  // {
  //   firstName: "Alvera",
  //   lastName: "Baford",
  //   age: 61,
  //   visits: 761,
  //   progress: 23.66,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Innis",
  //   lastName: "Masden",
  //   age: 64,
  //   visits: 821,
  //   progress: 31.55,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Zea",
  //   lastName: "Caccavella",
  //   age: 56,
  //   visits: 80,
  //   progress: 79.49,
  //   status: "active",
  // },
  // {
  //   firstName: "Zolly",
  //   lastName: "Murgatroyd",
  //   age: 53,
  //   visits: 77,
  //   progress: 99.76,
  //   status: "pending",
  // },
  // {
  //   firstName: "Filmore",
  //   lastName: "Yarham",
  //   age: 39,
  //   visits: 922,
  //   progress: 26.89,
  //   status: "pending",
  // },
  // {
  //   firstName: "Jay",
  //   lastName: "Meni",
  //   age: 46,
  //   visits: 784,
  //   progress: 27.96,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Duffie",
  //   lastName: "Gettings",
  //   age: 27,
  //   visits: 699,
  //   progress: 60.81,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Tremaine",
  //   lastName: "Maruska",
  //   age: 71,
  //   visits: 570,
  //   progress: 85.23,
  //   status: "active",
  // },
  // {
  //   firstName: "Alf",
  //   lastName: "McLagain",
  //   age: 18,
  //   visits: 551,
  //   progress: 54.86,
  //   status: "pending",
  // },
  // {
  //   firstName: "Yale",
  //   lastName: "Coghlan",
  //   age: 18,
  //   visits: 54,
  //   progress: 50.96,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Gerhard",
  //   lastName: "Ellacott",
  //   age: 82,
  //   visits: 972,
  //   progress: 61.05,
  //   status: "active",
  // },
  // {
  //   firstName: "Ginelle",
  //   lastName: "Tourle",
  //   age: 51,
  //   visits: 885,
  //   progress: 20.15,
  //   status: "pending",
  // },
  // {
  //   firstName: "Davy",
  //   lastName: "Warhurst",
  //   age: 30,
  //   visits: 927,
  //   progress: 13.02,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Kerwinn",
  //   lastName: "Hacquard",
  //   age: 30,
  //   visits: 186,
  //   progress: 49.43,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Riobard",
  //   lastName: "Oaks",
  //   age: 78,
  //   visits: 368,
  //   progress: 83.24,
  //   status: "pending",
  // },
  // {
  //   firstName: "Raynell",
  //   lastName: "Nafzger",
  //   age: 27,
  //   visits: 283,
  //   progress: 80.31,
  //   status: "pending",
  // },
  // {
  //   firstName: "Eduardo",
  //   lastName: "Chainey",
  //   age: 65,
  //   visits: 850,
  //   progress: 58.65,
  //   status: "active",
  // },
  // {
  //   firstName: "Saunders",
  //   lastName: "Pagen",
  //   age: 57,
  //   visits: 131,
  //   progress: 55.91,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Cynthy",
  //   lastName: "Coull",
  //   age: 56,
  //   visits: 216,
  //   progress: 87.0,
  //   status: "active",
  // },
  // {
  //   firstName: "Kennie",
  //   lastName: "Barthot",
  //   age: 21,
  //   visits: 665,
  //   progress: 87.3,
  //   status: "active",
  // },
  // {
  //   firstName: "Annora",
  //   lastName: "Humphery",
  //   age: 76,
  //   visits: 779,
  //   progress: 54.3,
  //   status: "active",
  // },
  // {
  //   firstName: "Dominique",
  //   lastName: "Navaro",
  //   age: 34,
  //   visits: 540,
  //   progress: 14.47,
  //   status: "active",
  // },
  // {
  //   firstName: "Paige",
  //   lastName: "Gronaller",
  //   age: 78,
  //   visits: 183,
  //   progress: 56.18,
  //   status: "pending",
  // },
  // {
  //   firstName: "Karlee",
  //   lastName: "Skule",
  //   age: 26,
  //   visits: 7,
  //   progress: 15.62,
  //   status: "active",
  // },
  // {
  //   firstName: "Holly",
  //   lastName: "Britian",
  //   age: 48,
  //   visits: 495,
  //   progress: 65.8,
  //   status: "active",
  // },
  // {
  //   firstName: "Cicily",
  //   lastName: "Cockshutt",
  //   age: 25,
  //   visits: 626,
  //   progress: 73.94,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Mal",
  //   lastName: "Grealey",
  //   age: 76,
  //   visits: 497,
  //   progress: 79.47,
  //   status: "active",
  // },
  // {
  //   firstName: "Appolonia",
  //   lastName: "Clementson",
  //   age: 31,
  //   visits: 497,
  //   progress: 2.62,
  //   status: "pending",
  // },
  // {
  //   firstName: "Byrle",
  //   lastName: "Norheny",
  //   age: 27,
  //   visits: 768,
  //   progress: 93.78,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Lotti",
  //   lastName: "Hellmer",
  //   age: 84,
  //   visits: 907,
  //   progress: 22.23,
  //   status: "active",
  // },
  // {
  //   firstName: "Wilfred",
  //   lastName: "Accum",
  //   age: 29,
  //   visits: 975,
  //   progress: 68.68,
  //   status: "active",
  // },
  // {
  //   firstName: "Debee",
  //   lastName: "Hirthe",
  //   age: 65,
  //   visits: 91,
  //   progress: 31.29,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Carlyle",
  //   lastName: "Rosenblum",
  //   age: 58,
  //   visits: 997,
  //   progress: 9.39,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Ilysa",
  //   lastName: "Nafzger",
  //   age: 58,
  //   visits: 62,
  //   progress: 44.83,
  //   status: "active",
  // },
  // {
  //   firstName: "Maggy",
  //   lastName: "Stokey",
  //   age: 18,
  //   visits: 95,
  //   progress: 29.58,
  //   status: "pending",
  // },
  // {
  //   firstName: "Audrey",
  //   lastName: "Dorrity",
  //   age: 56,
  //   visits: 473,
  //   progress: 22.91,
  //   status: "active",
  // },
  // {
  //   firstName: "Saba",
  //   lastName: "Brech",
  //   age: 47,
  //   visits: 888,
  //   progress: 28.14,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Milissent",
  //   lastName: "Darby",
  //   age: 30,
  //   visits: 221,
  //   progress: 69.86,
  //   status: "pending",
  // },
  // {
  //   firstName: "Morganne",
  //   lastName: "Arnet",
  //   age: 47,
  //   visits: 95,
  //   progress: 33.16,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Putnem",
  //   lastName: "Gideon",
  //   age: 76,
  //   visits: 251,
  //   progress: 39.74,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Urbanus",
  //   lastName: "Stove",
  //   age: 35,
  //   visits: 497,
  //   progress: 90.13,
  //   status: "active",
  // },
  // {
  //   firstName: "Mikol",
  //   lastName: "Joselevitch",
  //   age: 36,
  //   visits: 620,
  //   progress: 64.96,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Florry",
  //   lastName: "Kingshott",
  //   age: 51,
  //   visits: 828,
  //   progress: 11.58,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Anastassia",
  //   lastName: "Aisman",
  //   age: 32,
  //   visits: 0,
  //   progress: 41.92,
  //   status: "pending",
  // },
  // {
  //   firstName: "Kelly",
  //   lastName: "Cordey",
  //   age: 40,
  //   visits: 683,
  //   progress: 58.96,
  //   status: "active",
  // },
  // {
  //   firstName: "Free",
  //   lastName: "Clinnick",
  //   age: 63,
  //   visits: 216,
  //   progress: 34.18,
  //   status: "active",
  // },
  // {
  //   firstName: "Minnaminnie",
  //   lastName: "Carroll",
  //   age: 43,
  //   visits: 683,
  //   progress: 6.85,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Preston",
  //   lastName: "Braams",
  //   age: 60,
  //   visits: 356,
  //   progress: 54.19,
  //   status: "active",
  // },
  // {
  //   firstName: "Anette",
  //   lastName: "Gusney",
  //   age: 80,
  //   visits: 974,
  //   progress: 89.74,
  //   status: "pending",
  // },
  // {
  //   firstName: "Gianna",
  //   lastName: "Gardner",
  //   age: 72,
  //   visits: 472,
  //   progress: 85.1,
  //   status: "active",
  // },
  // {
  //   firstName: "Perri",
  //   lastName: "Frankowski",
  //   age: 37,
  //   visits: 99,
  //   progress: 41.38,
  //   status: "pending",
  // },
  // {
  //   firstName: "Clair",
  //   lastName: "Thunderman",
  //   age: 80,
  //   visits: 752,
  //   progress: 47.92,
  //   status: "active",
  // },
  // {
  //   firstName: "Estelle",
  //   lastName: "Artharg",
  //   age: 48,
  //   visits: 979,
  //   progress: 42.86,
  //   status: "active",
  // },
  // {
  //   firstName: "Charlean",
  //   lastName: "Francombe",
  //   age: 64,
  //   visits: 855,
  //   progress: 23.5,
  //   status: "active",
  // },
  // {
  //   firstName: "Miriam",
  //   lastName: "Pegg",
  //   age: 62,
  //   visits: 252,
  //   progress: 48.52,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Oralle",
  //   lastName: "Screas",
  //   age: 45,
  //   visits: 138,
  //   progress: 98.51,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Drud",
  //   lastName: "Paulazzi",
  //   age: 25,
  //   visits: 711,
  //   progress: 28.6,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Tabbatha",
  //   lastName: "Gircke",
  //   age: 20,
  //   visits: 216,
  //   progress: 36.49,
  //   status: "pending",
  // },
  // {
  //   firstName: "Rab",
  //   lastName: "Rastall",
  //   age: 29,
  //   visits: 596,
  //   progress: 64.86,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Timothea",
  //   lastName: "Norwood",
  //   age: 59,
  //   visits: 443,
  //   progress: 20.96,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Cobb",
  //   lastName: "Boys",
  //   age: 74,
  //   visits: 466,
  //   progress: 59.17,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Caria",
  //   lastName: "Pinel",
  //   age: 25,
  //   visits: 599,
  //   progress: 92.78,
  //   status: "pending",
  // },
  // {
  //   firstName: "Maxi",
  //   lastName: "Ransbury",
  //   age: 31,
  //   visits: 506,
  //   progress: 93.06,
  //   status: "pending",
  // },
  // {
  //   firstName: "Fiann",
  //   lastName: "Klosa",
  //   age: 36,
  //   visits: 441,
  //   progress: 2.2,
  //   status: "active",
  // },
  // {
  //   firstName: "Millicent",
  //   lastName: "Champken",
  //   age: 18,
  //   visits: 721,
  //   progress: 51.89,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Dewey",
  //   lastName: "Oxlee",
  //   age: 44,
  //   visits: 41,
  //   progress: 69.43,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Daryn",
  //   lastName: "Epine",
  //   age: 41,
  //   visits: 153,
  //   progress: 55.83,
  //   status: "pending",
  // },
  // {
  //   firstName: "Francoise",
  //   lastName: "Spurling",
  //   age: 28,
  //   visits: 663,
  //   progress: 42.14,
  //   status: "active",
  // },
  // {
  //   firstName: "Ileane",
  //   lastName: "Brown",
  //   age: 75,
  //   visits: 598,
  //   progress: 26.9,
  //   status: "inactive",
  // },
  // {
  //   firstName: "De witt",
  //   lastName: "Edgcumbe",
  //   age: 76,
  //   visits: 143,
  //   progress: 29.28,
  //   status: "pending",
  // },
  // {
  //   firstName: "Alano",
  //   lastName: "Danjoie",
  //   age: 57,
  //   visits: 40,
  //   progress: 26.78,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Yorke",
  //   lastName: "Kellitt",
  //   age: 29,
  //   visits: 710,
  //   progress: 89.92,
  //   status: "active",
  // },
  // {
  //   firstName: "Aurilia",
  //   lastName: "Ferras",
  //   age: 73,
  //   visits: 737,
  //   progress: 14.13,
  //   status: "active",
  // },
  // {
  //   firstName: "Mickey",
  //   lastName: "Lindegard",
  //   age: 26,
  //   visits: 135,
  //   progress: 81.91,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Dulciana",
  //   lastName: "Swinnerton",
  //   age: 80,
  //   visits: 905,
  //   progress: 30.19,
  //   status: "pending",
  // },
  // {
  //   firstName: "Rudd",
  //   lastName: "Elsey",
  //   age: 44,
  //   visits: 352,
  //   progress: 52.29,
  //   status: "pending",
  // },
  // {
  //   firstName: "Matthaeus",
  //   lastName: "Hinkensen",
  //   age: 40,
  //   visits: 162,
  //   progress: 81.98,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Catlaina",
  //   lastName: "Apfelmann",
  //   age: 79,
  //   visits: 292,
  //   progress: 9.64,
  //   status: "pending",
  // },
  // {
  //   firstName: "Gamaliel",
  //   lastName: "Basford",
  //   age: 28,
  //   visits: 159,
  //   progress: 99.69,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Vallie",
  //   lastName: "Errigo",
  //   age: 42,
  //   visits: 255,
  //   progress: 48.88,
  //   status: "active",
  // },
  // {
  //   firstName: "Federica",
  //   lastName: "Kedge",
  //   age: 19,
  //   visits: 590,
  //   progress: 54.9,
  //   status: "active",
  // },
  // {
  //   firstName: "Fanechka",
  //   lastName: "Snary",
  //   age: 23,
  //   visits: 333,
  //   progress: 49.79,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Em",
  //   lastName: "Paulley",
  //   age: 46,
  //   visits: 611,
  //   progress: 25.85,
  //   status: "active",
  // },
  // {
  //   firstName: "Kip",
  //   lastName: "Garlicke",
  //   age: 75,
  //   visits: 768,
  //   progress: 54.56,
  //   status: "pending",
  // },
  // {
  //   firstName: "Mirabel",
  //   lastName: "Southey",
  //   age: 56,
  //   visits: 766,
  //   progress: 21.06,
  //   status: "active",
  // },
  // {
  //   firstName: "Sheeree",
  //   lastName: "Janacek",
  //   age: 56,
  //   visits: 955,
  //   progress: 59.08,
  //   status: "pending",
  // },
  // {
  //   firstName: "Ransell",
  //   lastName: "Bligh",
  //   age: 70,
  //   visits: 198,
  //   progress: 75.43,
  //   status: "active",
  // },
  // {
  //   firstName: "Netty",
  //   lastName: "Hassin",
  //   age: 56,
  //   visits: 533,
  //   progress: 90.81,
  //   status: "inactive",
  // },
  // {
  //   firstName: "Maxy",
  //   lastName: "Moodie",
  //   age: 26,
  //   visits: 667,
  //   progress: 94.03,
  //   status: "active",
  // },
  // {
  //   firstName: "Torr",
  //   lastName: "Primo",
  //   age: 43,
  //   visits: 62,
  //   progress: 56.07,
  //   status: "active",
  // },
  // {
  //   firstName: "Wallace",
  //   lastName: "Gogin",
  //   age: 72,
  //   visits: 999,
  //   progress: 17.04,
  //   status: "active",
  // },
  // {
  //   firstName: "Oralee",
  //   lastName: "Le Marquis",
  //   age: 79,
  //   visits: 401,
  //   progress: 97.39,
  //   status: "inactive",
  // },
];
